# -*- coding: utf-8 -*-
{
    'name': "SW - HR Attendance ZKTeco",
    'summary': """Integration with ZKTeco Biometric Devices""",
    'description': "",
    'license': "Other proprietary",
    'author': "Smart Way Business Solutions",
    'website': "https://www.smartway.co",
    'category': 'Human Resources',
    'version': '1.5',
    'depends': ['base', 'hr', 'portal', 'hr_contract', 'hr_attendance', 'resource', 'mail'],
    'data': [
        'data/zk_techo_data.xml',
        'security/biometricdevice_security.xml',
        'security/ir.model.access.csv',
        'wizard/upload_employee_views.xml',
        'wizard/transfer_data_views.xml',
        'views/res_config_settings_view.xml',
        'views/hr_attendance_view.xml',
        'views/biometricdevice_view.xml',
        'views/hr_extensionview.xml',
        'wizard/move_attendance_wizard_view.xml',
        'wizard/generate_missing_attendance.xml',
        'wizard/upload_employee_views.xml',
        'views/menuitem.xml',

    ],
    'images': ["static/description/image.png"],
    'price': 160,
    'currency': 'EUR',
    'installable': True,
    'auto_install': False,
    'application': False,
    'external_dependencies': {
        'python': ['pyzk'],
    },
    'external_dependencies': {
        'python': ['pyzk'],
    },
}
